# RNNの復習はここに

### nerの復習

###### データ読み込み
###### label encoding
###### 辞書作成　エンコード
###### データ分割
###### padding
###### 学習準備
###### モデルの定義
###### 学習ループ
###### 評価

In [ ]:
import pickle

In [ ]:
# ラベルデータ
with open('ner_dataset_labels.txt', 'rb') as fp:
    labels = pickle.load(fp)
# sentenceデータ
with open('ner_dataset_sentences.txt', 'rb') as fp:
    sentences = pickle.load(fp)

In [ ]:
sentences

In [5]:
labels

[['O', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['B-per', 'O', 'O', 'B-geo', 'I-geo', 'O'],
 ['O', 'O', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'B-org', 'O'],
 ['O', 'B-geo', 'I-geo', 'O', 'O', 'B-geo', 'O'],
 ['O', 'O', 'O', 'B-geo', 'O'],
 ['O', 'O', 'O', 'B-geo', 'I-geo', 'I-geo', 'I-geo', 'O'],
 ['O', 'O', 'O', 'O', 'B-org', 'I-org', 'O'],
 ['O', 'O', 'O', 'O', 'B-org', 'I-org', 'O'],
 ['B-geo', 'O', 'O', 'O', 'O', 'B-geo', 'O'],
 ['B-geo', 'I-geo', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['O', 'B-geo', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['O', 'B-geo', 'O', 'O', 'O', 'B-geo', 'O'],
 ['O', 'B-geo', 'O', 'O', 'O', 'B-geo', 'O'],
 ['O', 'O', 'O', 'B-org', 'O'],
 ['O', 'O', 'O', 'B-geo', 'O'],
 ['O', 'O', 'O', 'O', 'B-geo', 'O', 'O', 'O', 'O'],
 ['O', 'B-geo', 'O', 'O', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'B-org', 'O'],
 ['B-per', 'I-per', 'O', 'O', 'O', 'O', 'O'],
 ['B-per', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['B-per', 'I-per', 'O', 'O', 'O', 'O'],
 ['O', 'B-geo', 'I-geo', 'I-geo', 'I-geo', '

### label encoding

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [7]:
# まず、全てのラベルを取得するために全データで1つのリストにする
all_labels = [label for sublabel in labels for label in sublabel]

# これに対してlabel encoderのfit
label_encoder.fit(all_labels) # labelのidを作成する

# labelsに対して適用する。padding用に+1することに注意
encodered_labels = [label_encoder.transform(sublabel) + 1 for sublabel in labels]

In [8]:
encodered_labels

[array([7, 7, 7, 7, 7, 7, 7]),
 array([3, 7, 7, 1, 4, 7]),
 array([7, 7, 7, 7, 7]),
 array([7, 7, 7, 2, 7]),
 array([7, 1, 4, 7, 7, 1, 7]),
 array([7, 7, 7, 1, 7]),
 array([7, 7, 7, 1, 4, 4, 4, 7]),
 array([7, 7, 7, 7, 2, 5, 7]),
 array([7, 7, 7, 7, 2, 5, 7]),
 array([1, 7, 7, 7, 7, 1, 7]),
 array([1, 4, 7, 7, 7, 7, 7, 7, 7, 7]),
 array([7, 1, 7, 7, 7, 7, 7, 7, 7, 7]),
 array([7, 1, 7, 7, 7, 1, 7]),
 array([7, 1, 7, 7, 7, 1, 7]),
 array([7, 7, 7, 2, 7]),
 array([7, 7, 7, 1, 7]),
 array([7, 7, 7, 7, 1, 7, 7, 7, 7]),
 array([7, 1, 7, 7, 7, 7, 7]),
 array([7, 7, 7, 2, 7]),
 array([3, 6, 7, 7, 7, 7, 7]),
 array([3, 7, 7, 7, 7, 7, 7, 7]),
 array([3, 6, 7, 7, 7, 7]),
 array([7, 1, 4, 4, 4, 7, 7, 1, 7]),
 array([7, 1, 4, 4, 7, 7, 1, 7]),
 array([7, 7, 7, 2, 7]),
 array([7, 1, 4, 7, 7, 1, 7]),
 array([7, 7, 7, 7, 7, 2, 5, 5, 7]),
 array([7, 7, 7, 1, 4, 7]),
 array([7, 7, 7, 1, 7, 7, 7]),
 array([7, 7, 7, 7, 2, 5, 5, 7])]

### 辞書作成 エンコード

In [9]:
word2indx = {'<PAD>':0}
encodered_sentences = []
for sentence in sentences:
    encodered_sentence = [word2indx.setdefault(word, len(word2indx)) for word in sentence.split() ]
    encodered_sentences.append(encodered_sentence) # ここでようやく2次元に 

In [10]:
encodered_sentences

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 7],
 [13, 14, 15, 16, 7],
 [17, 18, 19, 20, 7],
 [1, 21, 22, 23, 10, 24, 7],
 [25, 23, 26, 27, 7],
 [13, 28, 5, 29, 30, 31, 32, 7],
 [17, 23, 33, 19, 34, 35, 7],
 [25, 18, 36, 5, 37, 38, 7],
 [39, 23, 5, 40, 31, 41, 7],
 [42, 43, 23, 5, 44, 45, 10, 5, 46, 7],
 [1, 47, 23, 5, 48, 49, 10, 5, 46, 7],
 [1, 50, 51, 52, 10, 53, 7],
 [1, 54, 55, 23, 10, 56, 7],
 [13, 57, 19, 58, 7],
 [17, 23, 26, 59, 7],
 [25, 23, 60, 61, 24, 36, 62, 63, 7],
 [1, 64, 23, 5, 65, 66, 7],
 [25, 67, 19, 68, 7],
 [69, 70, 23, 62, 71, 72, 7],
 [73, 23, 74, 36, 75, 76, 77, 7],
 [78, 79, 80, 62, 81, 7],
 [1, 82, 22, 31, 83, 23, 10, 84, 7],
 [1, 29, 85, 86, 23, 10, 59, 7],
 [17, 18, 19, 87, 7],
 [1, 88, 89, 23, 10, 90, 7],
 [17, 23, 33, 19, 5, 35, 31, 91, 7],
 [25, 9, 10, 92, 93, 7],
 [94, 51, 95, 96, 97, 98, 7],
 [25, 18, 36, 5, 99, 100, 101, 7]]

In [11]:
word2indx

{'<PAD>': 0,
 'The': 1,
 'cat': 2,
 'sat': 3,
 'on': 4,
 'the': 5,
 'mat': 6,
 '.': 7,
 'John': 8,
 'lives': 9,
 'in': 10,
 'New': 11,
 'York': 12,
 'I': 13,
 'have': 14,
 'two': 15,
 'dogs': 16,
 'She': 17,
 'works': 18,
 'at': 19,
 'Google': 20,
 'Eiffel': 21,
 'Tower': 22,
 'is': 23,
 'Paris': 24,
 'He': 25,
 'from': 26,
 'Spain': 27,
 'visited': 28,
 'Great': 29,
 'Wall': 30,
 'of': 31,
 'China': 32,
 'studying': 33,
 'Oxford': 34,
 'University': 35,
 'for': 36,
 'United': 37,
 'Nations': 38,
 'Berlin': 39,
 'capital': 40,
 'Germany': 41,
 'Mount': 42,
 'Everest': 43,
 'highest': 44,
 'peak': 45,
 'world': 46,
 'Nile': 47,
 'longest': 48,
 'river': 49,
 'Pyramids': 50,
 'are': 51,
 'located': 52,
 'Egypt': 53,
 'Sahara': 54,
 'desert': 55,
 'Africa': 56,
 'work': 57,
 'Microsoft': 58,
 'Australia': 59,
 'going': 60,
 'to': 61,
 'a': 62,
 'meeting': 63,
 'Amazon': 64,
 'largest': 65,
 'rainforest': 66,
 'studied': 67,
 'Harvard': 68,
 'Mona': 69,
 'Lisa': 70,
 'famous': 71,
 'painti

### 訓練データ、検証データに分割する

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_val, y_train, y_val, train_sentences, val_sentences = train_test_split(encodered_sentences, encodered_labels, sentences, test_size=0.3, random_state=42)

In [14]:
print(X_train[:1])
print(y_train[:1])
print(train_sentences[:1])

[[1, 2, 3, 4, 5, 6, 7]]
[array([7, 7, 7, 7, 7, 7, 7])]
['The cat sat on the mat .']


In [15]:
from torch.nn.utils.rnn import pad_sequence
import torch

### padding

In [16]:
X_train = pad_sequence([torch.tensor(x) for x in X_train], batch_first=True)
X_val = pad_sequence([torch.tensor(x) for x in X_val], batch_first=True)
y_train = pad_sequence([torch.tensor(y) for y in y_train], batch_first=True)
y_val = pad_sequence([torch.tensor(y) for y in y_val], batch_first=True)

### モデルの定義　

In [1]:
import torch.nn as nn
from mymodel import MyUGRNN, MyGRU, MyLSTM # 自作モジュール
import torch
%load_ext autoreload
%autoreload 

In [6]:
### 自作のモデルが動くかテスト
vocab_size = 30 # データセット内での最大文字数
embeling_dim = 10 # 各単語のベクトルの次元
batch_size = 8
# num_classes = 3
hidden_size = 9
input_tensor = torch.randn((batch_size, vocab_size, embeling_dim))
test_model = MyLSTM(embeling_dim, hidden_size)

In [11]:
output_seq, (h_n, c_n) = test_model(input_tensor)

In [12]:
output_seq.shape

torch.Size([8, 30, 9])

In [13]:
h_n.shape

torch.Size([1, 8, 9])

In [14]:
c_n.shape

torch.Size([1, 8, 9])