### Gensim

In [2]:
# colabの準備
from google.colab import drive
drive_path = '/content/drive'
drive.mount(drive_path)
import sys
now_path = drive_path + "/MyDrive/深層学習"
sys.path.append(now_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
! pip install gensim

In [3]:
from gensim.models import KeyedVectors

In [7]:
KeyedVectors

gensim.models.keyedvectors.KeyedVectors

### GoogleNews-vectors-negative300.binモデルはCBOWを使用して学習されています。
###### このモデルの詳細については以下のポイントが重要です:
###### Googleが独自のコーパスを使用して学習したモデルです。
###### 約1,000億語のGoogle Newsデータセットの一部を使用して学習されています。
###### 300万語の単語とフレーズの300次元ベクトルが含まれています。
###### CBOWアーキテクチャを使用して学習されており、skip-gramバージョンは公開されていません。
###### gensim.models.KeyedVectorsを使用してこのモデルを読み込む際、CBOWかskip-gramかを指定する必要はありません。モデルファイル自体にアーキテクチャの情報が含まれているためです。

In [4]:
# モデルファイルのロード
word2Vec = KeyedVectors.load_word2vec_format(now_path + "/GoogleNews-vectors-negative300.bin", binary=True)

In [26]:
# word embedding
word_vecter = word2Vec['computer']
print(word_vecter)
word_vecter.shape  # 300次元のベクトル

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

(300,)

In [27]:
# 類似の単語を取得する(デフォルトで10個)
# 出てくるのはコサイン類似度
word2Vec.most_similar('computer')

[('computers', 0.7979379892349243),
 ('laptop', 0.6640493273735046),
 ('laptop_computer', 0.6548868417739868),
 ('Computer', 0.647333562374115),
 ('com_puter', 0.6082080006599426),
 ('technician_Leonard_Luchko', 0.5662748217582703),
 ('mainframes_minicomputers', 0.5617720484733582),
 ('laptop_computers', 0.5585449934005737),
 ('PC', 0.5539618730545044),
 ('maker_Dell_DELL.O', 0.5519254207611084)]

In [28]:
# 類似度を計算する
word2Vec.similarity('woman', 'man')

0.76640123

In [33]:
# kimg - man + woman
result_vecter = word2Vec['king'] - word2Vec['man'] + word2Vec['woman']  # - word2Vec['male'] + word2Vec['female']
similar_words = word2Vec.most_similar(result_vecter)
print(similar_words)

[('king', 0.8449392318725586), ('queen', 0.7300517559051514), ('monarch', 0.645466148853302), ('princess', 0.6156251430511475), ('crown_prince', 0.5818676352500916), ('prince', 0.5777117609977722), ('kings', 0.5613663792610168), ('sultan', 0.5376775860786438), ('Queen_Consort', 0.5344247817993164), ('queens', 0.5289887189865112)]


### Spacy

###### GloVeをベースにしたアルゴリズム

In [34]:
! pip install spacy

In [35]:
import spacy

In [38]:
# モデルのロード
nlp = spacy.load('en_core_web_sm') # Natural Language Processing

In [46]:
# world embedding
print(nlp('computer').vector)
print(nlp('computer').vector.shape)

[-1.6373895  -0.6080451  -0.6566559  -0.10872576 -0.24852699  0.17527935
  0.7263826   1.658519   -0.1795105  -0.57576895  0.2937798  -1.0000906
 -0.29037115 -0.21647847 -0.03370228  0.7057948  -0.7825656  -1.2829045
  1.3557242   0.8119894   0.6912364   0.57129043 -0.33364248 -1.0607941
  0.8841657   0.25746697 -0.03119813  0.7934418   0.11529171  0.27637503
 -0.3697168   0.8258281   1.3755571   0.55934906 -0.52683127 -1.1254272
  0.20773923  0.47141504  0.38074216 -0.7482727  -0.07192928 -0.063835
 -0.5294903   1.2106018  -0.67606175 -0.47462302 -0.9633928   1.2195504
  0.205295   -0.22966453  0.32949054  1.4156418   1.0020167  -1.0212331
  0.24324086  0.15824679  0.63781977 -0.5370287   0.11409536 -0.44219247
 -0.9631854  -0.11269182  0.22333866 -0.07143135  1.0847998   0.8003227
 -0.18230852 -0.67244947  0.09219736 -0.5087909   0.4841568   1.1335273
  1.3780379  -0.4093325   0.00951386 -0.3827051  -0.5394529  -0.00996476
  0.17741328 -1.2335469   0.32314333 -0.4584407  -2.109942   

In [44]:
# 類似度を取得
nlp('woman').similarity(nlp('man'))  # 0.9191394603322555

<ipython-input-44-e41c63190dc3>:2: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  nlp('woman').similarity(nlp('man'))


0.9191394603322555

### FastText (with Gensim)

gensim.models.FastTextクラスは、FastTextアルゴリズムを実装した単語埋め込みモデルを作成・学習するためのクラスです。主な特徴は以下の通りです:
##### Word2Vecの拡張: FastTextはWord2Vecを基にしており、gensim.models.Word2Vecクラスを継承しています。
##### サブワード情報の利用: 単語をn-gramに分解し、サブワード情報を活用することで、未知語や稀少語に対してもベクトル表現を生成できます。
##### 学習方法: CBOWとskip-gramの両方の学習方法をサポートしています。
モデルの保存と読み込み: 学習したモデルの保存や、事前学習済みモデルの読み込みが可能です。
##### 未知語への対応: 学習データに存在しない単語に対してもベクトル表現を生成できます。
##### 多言語対応: さまざまな言語のテキストデータで学習可能です。
ハイパーパラメータ: ベクトルサイズ、ウィンドウサイズ、最小出現回数、エポック数など、多くのパラメータを調整できます。

In [47]:
import gensim.downloader as api

In [49]:
# text8のデータセットの情報
api.info('text8')

{'num_records': 1701,
 'record_format': 'list of str (tokens)',
 'file_size': 33182058,
 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/text8/__init__.py',
 'license': 'not found',
 'description': 'First 100,000,000 bytes of plain text from Wikipedia. Used for testing purposes; see wiki-english-* for proper full Wikipedia datasets.',
 'checksum': '68799af40b6bda07dfa47a32612e5364',
 'file_name': 'text8.gz',
 'read_more': ['http://mattmahoney.net/dc/textdata.html'],
 'parts': 1}

In [50]:
dataset = api.load('text8')

[==================================================] 100.0% 31.6/31.6MB downloaded


In [55]:
next(iter(dataset))[:10]

['anarchism',
 'originated',
 'as',
 'a',
 'term',
 'of',
 'abuse',
 'first',
 'used',
 'against']

In [56]:
# 学習
import time
from gensim.models import FastText
# FastTextモデルでは、sgパラメータを使ってCBOWとskip-gramを切り替えることができる:
# sg=0（デフォルト値）: CBOWモデルを使用
# sg=1: Skip-gramモデルを使用
start_time = time.time()
model = FastText(dataset, vector_size=100, window=5, min_count=5,workers=4)
end_time = time.time()
training_time = end_time - start_time
print(f"Training took {training_time:2f}")

Training took 683.738658


In [57]:
# word embeling
model.wv['computer']

array([-0.6310219 , -0.43088117, -0.73242086, -0.8479438 ,  0.13219036,
       -1.3451334 , -0.6716183 ,  2.8736567 , -0.7191575 , -2.014758  ,
        0.2759506 , -1.5634896 ,  3.1581528 ,  3.1189227 ,  2.1013887 ,
       -0.655212  , -3.011386  , -1.0436983 ,  1.1530657 , -0.12958491,
        0.23828767, -1.7438835 ,  1.5098817 ,  2.245927  ,  0.7163654 ,
        1.4178075 , -2.6695218 , -1.2843001 , -1.7613577 , -1.0593234 ,
        0.4105746 ,  2.6161335 , -0.04117085,  2.2675288 ,  0.73867416,
        1.5392488 ,  0.4401874 ,  0.192323  , -1.7538459 , -1.4514574 ,
       -0.18741283, -1.428633  ,  1.043824  ,  3.0407867 , -0.47679445,
       -2.3920453 , -2.5954747 , -1.3189179 ,  0.20542304, -2.408414  ,
        1.658689  ,  0.264226  , -0.8284922 , -0.03770952, -0.1764593 ,
        1.8826362 ,  1.2724019 ,  0.0724032 , -0.2232734 , -0.81018037,
        0.8099029 ,  1.9850342 , -0.78439814, -0.602875  , -0.01670636,
        0.51287323,  0.3230763 ,  2.4051225 ,  1.0771964 ,  0.08

In [59]:
similarity = model.wv.similarity('computer', 'software')
similarity

0.7296425

### Embedding Layer

In [5]:
import torch

In [6]:
# embedding matrix
vocab_size = len(word2Vec) # 3000000 実際には手元データのvocab sizeを指定する
enbedding_dim = 300 # 300次元のデータ

embedding_matrix = torch.zeros((vocab_size, enbedding_dim))
for i, word in enumerate(word2Vec.key_to_index.keys()):
  embedding_matrix[i] = torch.from_numpy(word2Vec[word])

<ipython-input-6-54cda6a3b71f>:7: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  embedding_matrix[i] = torch.from_numpy(word2Vec[word])


In [8]:
embedding_matrix.shape
print(embedding_matrix)

tensor([[ 1.1292e-03, -8.9645e-04,  3.1853e-04,  ..., -1.5640e-03,
         -1.2302e-04, -8.6308e-05],
        [ 7.0312e-02,  8.6914e-02,  8.7891e-02,  ..., -4.7607e-02,
          1.4465e-02, -6.2500e-02],
        [-1.1780e-02, -4.7363e-02,  4.4678e-02,  ...,  7.1289e-02,
         -3.4912e-02,  2.4170e-02],
        ...,
        [-1.9653e-02, -9.0820e-02, -1.9409e-02,  ..., -1.6357e-02,
         -1.3428e-02,  4.6631e-02],
        [ 3.2715e-02, -3.2227e-02,  3.6133e-02,  ..., -8.8501e-03,
          2.6978e-02,  1.9043e-02],
        [ 4.5166e-02, -4.5166e-02, -3.9368e-03,  ...,  7.9590e-02,
          7.2266e-02,  1.3000e-02]])


In [9]:
# embedding layerの挙動を確認する
import torch.nn as nn
embedding_layer = nn.Embedding.from_pretrained(embedding_matrix, freeze=False)

In [12]:
# forwardのテスト
text = torch.tensor([[1, 2, 3], [4, 5, 6]])
out = embedding_layer(text)

In [13]:
out

tensor([[[ 0.0703,  0.0869,  0.0879,  ..., -0.0476,  0.0145, -0.0625],
         [-0.0118, -0.0474,  0.0447,  ...,  0.0713, -0.0349,  0.0242],
         [-0.0157, -0.0283,  0.0835,  ...,  0.0069,  0.0610, -0.1484]],

        [[ 0.0070, -0.0732,  0.1719,  ...,  0.0112,  0.1641,  0.1069],
         [ 0.0267, -0.0908,  0.0278,  ..., -0.1167, -0.0294, -0.0708],
         [ 0.1689, -0.0630, -0.0003,  ...,  0.0238, -0.1235,  0.0164]]],
       grad_fn=<EmbeddingBackward0>)

In [19]:
# 単語とその埋め込みベクトルの確認
i, j = 0, 0
word = list(word2Vec.key_to_index.keys())[text[i, j]]
print(f"word : {word}")
embedding_layer(text[i, j])
assert torch.all(embedding_layer(text[i, j]) == embedding_layer(text[i, j]))

word : in


In [21]:
# 重みから直接indexした結果
assert torch.all(embedding_layer.weight[text, :] == out)

tensor(True)

### 補足

In [16]:
count = 0
for word in word2Vec.key_to_index.keys():
  if count <= 4:
    print(word)# key (computerなど)をイテレーションで返してくれる
    count += 1
  else:
    break

</s>
in
for
that
is


In [22]:
# asert
# Pythonのassertは、プログラム内で条件をチェックし、その条件が偽の場合にエラーを発生させるためのデバッグツール
assert 10 > 9

In [23]:
assert 10 < 9

AssertionError: 